
/* THIS FILE IS AUTO-GENERATED BY Makefile */
#include "mp_version.h"
const int mp_version_major = MP_VERSION_MAJOR;
const int mp_version_minor = MP_VERSION_MINOR;
const int mp_version_patch = MP_VERSION_PATCH;
const char * const mp_version_string = "3.5.0-902bb87";
const char * const mp_version_component = "mod_python/" "3.5.0-902bb87";
